"""Add grade_restriction to Event table

Revision ID: 4014262c68e4
Revises: 
Create Date: 2025-10-25 12:22:11.741317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4014262c68e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('required_volunteers', sa.Integer(), nullable=False),
    sa.Column('current_volunteers', sa.Integer(), nullable=True),
    sa.Column('leader_name', sa.String(length=100), nullable=True),
    sa.Column('leader_contact', sa.String(length=100), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('grade_restriction', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('qq', sa.String(length=50), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profile_phone'), ['phone'], unique=True)

    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'event_id', name='_student_event_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profile_phone'))

    op.drop_table('student_profile')
    op.drop_table('event')
    # ### end Alembic commands ###
