"""Create event table

Revision ID: c20b2bd92bd5
Revises: 
Create Date: 2025-10-20 22:11:37.604174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20b2bd92bd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('required_volunteers', sa.Integer(), nullable=False),
    sa.Column('current_volunteers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('leader_name', sa.String(length=100), nullable=True),
    sa.Column('leader_contact', sa.String(length=100), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
