"""Initial migration with new Volunteer model

Revision ID: d928dbed8a0c
Revises: 
Create Date: 2025-10-24 22:02:51.897882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd928dbed8a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('required_volunteers', sa.Integer(), nullable=False),
    sa.Column('current_volunteers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('leader_name', sa.String(length=100), nullable=True),
    sa.Column('leader_contact', sa.String(length=100), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('qq', sa.String(length=50), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'event_id', name='_phone_event_uc')
    )
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_phone'))

    op.drop_table('volunteer')
    op.drop_table('event')
    # ### end Alembic commands ###
