"""Remove image_url from Event and add lookup APIs

Revision ID: efd585c1cdfd
Revises: d928dbed8a0c
Create Date: 2025-10-24 22:29:15.271026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd585c1cdfd'
down_revision = 'd928dbed8a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_phone'))
        batch_op.create_index(batch_op.f('ix_volunteer_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_name'))
        batch_op.create_index(batch_op.f('ix_volunteer_phone'), ['phone'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
